---
title: Bubblegame
description: Bet now!
image:
author:
lang: en
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
  - jekyll-seo-tag
twitter:
  username: playbubblegame
  card: summary
logo: https://res.cloudinary.com/bubblegame/image/upload/f_auto/logo
social:
  name: Bubblegame
  links:
    - https://twitter.com/playbubblegame
webmaster_verifications:
  google: freHE_n_Yk6GISr0it_jZhwymo1hVEgSxQ8XGnzV6ss
